name: Quickstart Doctor
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Quickstart Doctor
        run: npx -y @qsdoctor/quickstart-verify
